-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 18:21:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artigos` (
  `idArtigos` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Data de apresentação` INT NOT NULL,
  PRIMARY KEY (`idArtigos`));


-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `idInstituicao` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstituicao`));


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutores` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Artigos_id` INT NOT NULL,
  `Instituicao_ID` INT NOT NULL,
  PRIMARY KEY (`idAutores`),
  CONSTRAINT `fk_Autor_Artigos1`
    FOREIGN KEY (`Artigos_id`)
    REFERENCES `mydb`.`Artigos` (`idArtigos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_Instituicao1`
    FOREIGN KEY (`Instituicao_ID`)
    REFERENCES `mydb`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participantes` (
  `codigoParticipantes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoParticipantes`));


-- -----------------------------------------------------
-- Table `mydb`.`Participantes_has_Artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participantes_has_Artigos` (
  `Participantes_codigoParticipantes` INT NOT NULL,
  `Artigos_id` INT NOT NULL,
  PRIMARY KEY (`Participantes_codigoParticipantes`, `Artigos_id`),
  CONSTRAINT `fk_Participantes_has_Artigos_Participantes1`
    FOREIGN KEY (`Participantes_codigoParticipantes`)
    REFERENCES `mydb`.`Participantes` (`codigoParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participantes_has_Artigos_Artigos1`
    FOREIGN KEY (`Artigos_id`)
    REFERENCES `mydb`.`Artigos` (`idArtigos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Transfe Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transfe Banco` (
  `numeroDeTransferencia` INT NOT NULL,
  `data de transferencia` VARCHAR(10) NOT NULL,
  `Participantes_codigoParticipantes` INT NOT NULL,
  PRIMARY KEY (`numeroDeTransferencia`),
  CONSTRAINT `fk_Transfe Banco_Participantes1`
    FOREIGN KEY (`Participantes_codigoParticipantes`)
    REFERENCES `mydb`.`Participantes` (`codigoParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);