-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 18:14:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `preço` FLOAT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja` (
  `idLoja` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `e-mail opcional` VARCHAR(45) NULL,
  PRIMARY KEY (`idLoja`));


-- -----------------------------------------------------
-- Table `mydb`.`Loja_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja_has_Produto` (
  `Loja_idLoja` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`Loja_idLoja`, `Produto_id`),
  CONSTRAINT `fk_Loja_has_Produto_Loja`
    FOREIGN KEY (`Loja_idLoja`)
    REFERENCES `mydb`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loja_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CEP` INT NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `senha unica` VARCHAR(45) NOT NULL,
  `telefone opcional` INT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `senha unica_UNIQUE` (`senha unica` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Correio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Correio` (
  `idCorreio` INT NOT NULL,
  `prazo de entrega` INT NOT NULL,
  `Valor do frete` FLOAT NOT NULL,
  PRIMARY KEY (`idCorreio`),
  UNIQUE INDEX `idCorreio_UNIQUE` (`idCorreio` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Codigo de rastreio` INT NOT NULL,
  `tipo de pagamento` VARCHAR(45) NOT NULL,
  `valor total` FLOAT NOT NULL,
  `Correio_idCorreio` INT NOT NULL,
  PRIMARY KEY (`Codigo de rastreio`, `Correio_idCorreio`),
  UNIQUE INDEX `Codigo de rastreio_UNIQUE` (`Codigo de rastreio` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Correio1`
    FOREIGN KEY (`Correio_idCorreio`)
    REFERENCES `mydb`.`Correio` (`idCorreio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `Nota` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nota`, `Descricao`));


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Produto` (
  `Cliente_CPF` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`Cliente_CPF`, `Produto_id`),
  CONSTRAINT `fk_Cliente_has_Produto_Cliente2`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Produto_Produto2`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Avaliacao` (
  `Cliente_CPF` INT NOT NULL,
  `Avaliacao_Nota` INT NOT NULL,
  `Avaliacao_Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cliente_CPF`, `Avaliacao_Nota`, `Avaliacao_Descricao`),
  CONSTRAINT `fk_Cliente_has_Avaliacao_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Avaliacao_Avaliacao1`
    FOREIGN KEY (`Avaliacao_Nota` , `Avaliacao_Descricao`)
    REFERENCES `mydb`.`Avaliacao` (`Nota` , `Descricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
